---
- hosts: linux
  user: ansible
  become: true
  
  tasks:

  - name: Update packages in Rocky Server
    ansible.builtin.yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    notify: Reboot server

  - name: Update packages in Ubuntu Server
    ansible.builtin.apt:
      name: "*"
      state: latest
      update_cache: yes
    when: ansible_os_family == "Debian"
    notify: Reboot server
      
  - name: Install version 17 of OpenJDK at Rocky Server
    ansible.builtin.yum:
      name: java-17-openjdk
      state: latest
    when: ansible_os_family == "RedHat"

  - name: Install apache at Server Ubuntu
    ansible.builtin.apt:
      name: apache2
      state: present
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: Apache service initialized and enabled at Server Ubuntu
    ansible.builtin.systemd:
      name: apache2
      state: started
      enabled: true
    when: ansible_os_family == "Debian"    

  handlers:

  - name: Reboot server
    ansible.builtin.reboot:
      reboot_timeout: 300

