---
- name: Install Apache, make it a service, create a reverse proxy, install firewall, and configure it
  hosts: ubuntu
  user: ansible
  become: yes
  tasks:
    
  - name: Install Apache service
    apt:
      name: apache2
      state: present
      update_cache: yes

  - name: Start and enable Apache       
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: true

  - name: Configure Apache as a Reverse Proxy using a template
    ansible.builtin.template:
      src: httpd.conf.j2
      dest: /etc/apache2/sites-available/reverse_proxy.conf  
      owner: "root"
      group: "root"
      mode: "0644"
    notify: restart apache

  - name: Enable required Apache modules for Debian family
    ansible.builtin.command:
      cmd: "a2enmod proxy proxy_http proxy_balancer lbmethod_byrequests"
    when: ansible_facts['os_family'] == "Debian"    

  - name: Enable reverse proxy site configuration on Debian family
    ansible.builtin.command:
      cmd: "a2ensite reverse_proxy.conf"
    when: ansible_facts['os_family'] == "Debian"

  - name: Install ufw firewall
    apt:
      name: ufw
      state: present
      update_cache: yes

  - name: Enable ufw firewall
    ufw:
      state: enabled  

  - name: Allow access to Apache web server
    ufw:
      rule: allow
      port: 80
      proto: tcp

  - name: Allow SSH access
    ufw:
      rule: allow
      port: 22
      proto: tcp
        
  handlers:
  - name: restart apache
    service:
      name: apache2
      state: restarted
