---
- name: Install Apache, make it a service, create a reverse proxy, install firewall, and configure it
  hosts: ubuntu
  user: ansible
  become: yes
  tasks:
    
  - name: Install Apache service
    apt:
      name: apache2
      state: present
      update_cache: yes
  
  - name: Enable Apache mod_proxy and mod_proxy_http modules
    apache2_module:
      state: present
      name: "{{ item }}"
    loop:
      - proxy
      - proxy_http
      - proxy_balancer
      - lbmethod_byrequests
    notify: restart apache2

  - name: Copy Apache configuration file for reverse proxy
    template: 
      src: httpd.conf.j2
      dest: /etc/apache2/sites-available/000-default.conf
    notify: restart apache2

  - name: Start and enable Apache service
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Install ufw firewall
    apt:
      name: ufw
      state: present
      update_cache: yes

  - name: Enable ufw firewall
    ufw:
      state: enabled
        
  - name: Allow access to Apache web server
    ufw:
      rule: allow
      port: 80
      proto: tcp
       
  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted
