---
- name: Install Apache, make it service, create the reverse proxy, install firewall and configure it
  hosts: ubuntu
  user: ansible
  become: yes
  tasks:
    - name: Install Apache service
      apt:
        name: apache2
        state: present
        update_cache: yes  
    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Copy Apache configuration file for reverse proxy
      template:
        src: /home/sysadmin/tallerfebrero2024/httpd.conf.j2
        dest: /etc/apache2/apache2.conf
    - name: Install ufw firewall
      apt:
        name: ufw
        state: present
        update_cache: yes
    - name: Enable ufw as a service
      community.general.ufw:
        policy: allow
        state: enabled   
    - name: Allow access to Apache web server
      ufw:
        rule: allow
        port: 80
        proto: tcp
